import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
style={
    { 
      "--tx-1": (Math.random() - 0.5),
      "--ty-1": (Math.random() - 0.5),
      "--tx-2": (Math.random() - 0.5),
      "--ty-2": (Math.random() - 0.5),
      "--tx-3": (Math.random() - 0.5),
      "--ty-3": (Math.random() - 0.5),
      "--tx-4": (Math.random() - 0.5),
      "--ty-4": (Math.random() - 0.5),
    }
  } 

      >
        {children}
      </body>
    </html>
  );
}
